"""Form-spine correctness, especially the leakage rule.

A trailing window that includes the current game leaks the outcome into its own
feature. The model then looks brilliant offline and is worthless live. The
window bound must be `interval 1 day preceding` -- exclusive of today.
"""

from __future__ import annotations

import datetime

import duckdb
import pytest

from modeling.features import (
    FORM_SPINE_AB_SQL,
    FORM_SPINE_BAT_AB_SQL,
    FORM_SPINE_BAT_CONTACT_SQL,
    FORM_SPINE_SQL,
    LEAKAGE_BOUND,
    _windows,
)


@pytest.fixture()
def con():
    c = duckdb.connect()
    c.execute("set enable_progress_bar = false")
    # Three days for one pitcher. Day 3 is a total outlier: if any rolling
    # feature for day 3 reflects day 3, the leak is visible as a changed value.
    c.execute("""
        create table pitches as
        select * from (values
            (1, date '2024-04-01', 1, 100.0),
            (1, date '2024-04-01', 1, 100.0),
            (1, date '2024-04-02', 1, 100.0),
            (1, date '2024-04-02', 1, 100.0),
            (1, date '2024-04-03', 0,   1.0),
            (1, date '2024-04-03', 0,   1.0)
        ) as t(pitcher_id, game_date, in_zone, start_speed)
    """)
    return c


def _spine(con):
    con.execute(f"create table spine as {FORM_SPINE_SQL}")
    return {r[0]: r for r in con.execute(
        "select game_date, career_zone_rate, career_velo, career_n "
        "from spine order by game_date").fetchall()}


def test_first_day_has_no_prior_history(con):
    rows = _spine(con)
    first = rows[datetime.date(2024, 4, 1)]
    assert first[3] == 0 or first[1] is None, \
        "day 1 must have no prior rows -- there is no history before it"


def test_window_excludes_the_current_day(con):
    rows = _spine(con)
    day3 = rows[datetime.date(2024, 4, 3)]
    # Days 1-2 were all in-zone at 100 mph. Day 3 is 0% in-zone at 1 mph.
    # If day 3 leaked into its own feature these would be pulled toward 0.
    assert day3[1] == pytest.approx(1.0), \
        f"day 3 zone_rate {day3[1]} reflects day 3 -- LEAK"
    assert day3[2] == pytest.approx(100.0), \
        f"day 3 velo {day3[2]} reflects day 3 -- LEAK"
    assert day3[3] == 4, "day 3 should see exactly the 4 prior pitches"


def _window_clauses(sql: str) -> str:
    """The `window ... as (...)` tail, whitespace-normalised."""
    return " ".join(sql.rsplit("\nwindow\n", 1)[1].split())


ALL_SPINES = {
    "FORM_SPINE_SQL": (FORM_SPINE_SQL, "pitcher_id"),
    "FORM_SPINE_AB_SQL": (FORM_SPINE_AB_SQL, "pitcher_id"),
    "FORM_SPINE_BAT_AB_SQL": (FORM_SPINE_BAT_AB_SQL, "batter_id"),
    "FORM_SPINE_BAT_CONTACT_SQL": (FORM_SPINE_BAT_CONTACT_SQL, "batter_id"),
}


def test_every_spine_shares_one_leakage_bound():
    """Four spines, two subject keys, one bound.

    This used to compare two SQL texts and trust that whoever added a third
    would notice. They are now generated by `_windows()`, so the check is that
    each spine's tail IS that output -- a new spine writing its own clauses
    fails here rather than leaking quietly.
    """
    for name, (sql, key) in ALL_SPINES.items():
        assert _window_clauses(sql) == _window_clauses(_windows(key)), (
            f"{name} does not use the shared _windows({key!r}) clauses")
        assert _window_clauses(sql).count(LEAKAGE_BOUND) == 3, (
            f"{name} has a window that is not bounded exclusive of today")


def test_the_two_subject_keys_differ_only_in_the_partition():
    """A batter spine must measure the BATTER. Partitioning a batter spine by
    pitcher_id would still run, still produce plausible rates, and be
    measuring the wrong player entirely."""
    p = _window_clauses(_windows("pitcher_id"))
    b = _window_clauses(_windows("batter_id"))
    assert p != b
    assert p.replace("pitcher_id", "batter_id") == b

    for name, (sql, key) in ALL_SPINES.items():
        other = "batter_id" if key == "pitcher_id" else "pitcher_id"
        assert f"partition by {other}" not in _window_clauses(sql), name


def test_ab_spine_excludes_the_current_day():
    c = duckdb.connect()
    c.execute("""
        create table at_bats as
        select * from (values
            (1, date '2024-04-01', 'strikeout', 'strikeout'),
            (1, date '2024-04-02', 'strikeout', 'strikeout'),
            (1, date '2024-04-03', 'hit',       'home_run'),
            (1, date '2024-04-03', 'hit',       'home_run')
        ) as t(pitcher_id, game_date, result, result_detail)
    """)
    c.execute(f"create table spine as {FORM_SPINE_AB_SQL}")
    row = c.execute(
        "select career_k_rate, career_n, career_hit_rate, career_hr_rate "
        "from spine where game_date = date '2024-04-03'").fetchone()
    assert row[0] == pytest.approx(1.0), \
        f"day 3 k_rate {row[0]} reflects day 3's hits -- LEAK"
    assert row[1] == 2
    # hit and HR rates joined this spine for the batter markets. They must
    # obey the same bound as the k_rate that was already here.
    assert row[2] == pytest.approx(0.0), \
        f"day 3 hit_rate {row[2]} reflects day 3 -- LEAK"
    assert row[3] == pytest.approx(0.0), \
        f"day 3 hr_rate {row[3]} reflects day 3 -- LEAK"


# ── the batter spines ───────────────────────────────────────────────────────

def test_batter_ab_spine_excludes_the_current_day():
    """Same leak, the other side of the matchup.

    Days 1-2 are strikeouts; day 3 is two home runs. If day 3 reached its own
    window the hr_rate would read 1.0 and the model would be told, before the
    game, how the game went.
    """
    c = duckdb.connect()
    c.execute("""
        create table at_bats as
        select * from (values
            (1, date '2024-04-01', 'strikeout', 'strikeout'),
            (1, date '2024-04-02', 'strikeout', 'strikeout'),
            (1, date '2024-04-03', 'hit',       'home_run'),
            (1, date '2024-04-03', 'hit',       'home_run')
        ) as t(batter_id, game_date, result, result_detail)
    """)
    c.execute(f"create table spine as {FORM_SPINE_BAT_AB_SQL}")
    row = c.execute(
        "select career_k_rate, career_hr_rate, career_hit_rate, career_n "
        "from spine where game_date = date '2024-04-03'").fetchone()
    assert row[0] == pytest.approx(1.0), f"k_rate {row[0]} sees day 3 -- LEAK"
    assert row[1] == pytest.approx(0.0), f"hr_rate {row[1]} sees day 3 -- LEAK"
    assert row[2] == pytest.approx(0.0)
    assert row[3] == 2


def test_home_run_rate_reads_result_detail_not_result():
    """`result` collapses single/double/triple/home_run into one `hit` bucket.

    A spine reading `result` would score every hit as a home run and look
    entirely plausible doing it -- the rate would just be four times too high.
    """
    c = duckdb.connect()
    c.execute("""
        create table at_bats as
        select * from (values
            (1, date '2024-04-01', 'hit', 'single'),
            (1, date '2024-04-01', 'hit', 'double'),
            (1, date '2024-04-01', 'hit', 'home_run'),
            (1, date '2024-04-01', 'out', 'field_out'),
            (1, date '2024-04-02', 'out', 'field_out')
        ) as t(batter_id, game_date, result, result_detail)
    """)
    c.execute(f"create table spine as {FORM_SPINE_BAT_AB_SQL}")
    row = c.execute(
        "select career_hit_rate, career_hr_rate from spine "
        "where game_date = date '2024-04-02'").fetchone()
    assert row[0] == pytest.approx(0.75), "three of four were hits"
    assert row[1] == pytest.approx(0.25), (
        f"hr_rate {row[1]} counts every hit as a home run")


def _contact_rows():
    """Two soft days, then one scorched pulled-fly day.

    Coordinates toward the left-field line, batting right-handed, so the day-3
    balls are pulled in the air -- the combination the rate exists to catch.
    """
    return """
        create table pitches as
        select * from (values
            (1, date '2024-04-01', 'in_play', 'R',  80.0, 'ground_ball', 125.42, 100.0),
            (1, date '2024-04-01', 'in_play', 'R',  80.0, 'ground_ball', 125.42, 100.0),
            (1, date '2024-04-02', 'in_play', 'R',  80.0, 'ground_ball', 125.42, 100.0),
            (1, date '2024-04-02', 'in_play', 'R',  80.0, 'ground_ball', 125.42, 100.0),
            (1, date '2024-04-03', 'in_play', 'R', 110.0, 'fly_ball',     60.0,  120.0),
            (1, date '2024-04-03', 'in_play', 'R', 110.0, 'fly_ball',     60.0,  120.0)
        ) as t(batter_id, game_date, result_category, bat_side,
               launch_speed, trajectory, hit_coord_x, hit_coord_y)
    """


def test_batter_contact_spine_excludes_the_current_day():
    c = duckdb.connect()
    c.execute(_contact_rows())
    c.execute(f"create table spine as {FORM_SPINE_BAT_CONTACT_SQL}")
    row = c.execute(
        "select career_hard_hit_rate, career_pull_air_rate, career_exit_velo, "
        "       career_n from spine where game_date = date '2024-04-03'"
    ).fetchone()
    assert row[0] == pytest.approx(0.0), f"hard_hit {row[0]} sees day 3 -- LEAK"
    assert row[1] == pytest.approx(0.0), f"pull_air {row[1]} sees day 3 -- LEAK"
    assert row[2] == pytest.approx(80.0), f"exit velo {row[2]} sees day 3 -- LEAK"
    assert row[3] == 4


def test_contact_spine_sees_prior_days_it_should():
    """The mirror of the leak test: a bound that excluded too much would pass
    every assertion above and measure nothing at all."""
    c = duckdb.connect()
    c.execute(_contact_rows())
    c.execute("""
        insert into pitches values
            (1, date '2024-04-04', 'in_play', 'R', 110.0, 'fly_ball', 60.0, 120.0)
    """)
    c.execute(f"create table spine as {FORM_SPINE_BAT_CONTACT_SQL}")
    row = c.execute(
        "select career_hard_hit_rate, career_pull_air_rate, career_n "
        "from spine where game_date = date '2024-04-04'").fetchone()
    # Four soft days plus the two scorched day-3 balls.
    assert row[2] == 6
    assert row[0] == pytest.approx(2 / 6)
    assert row[1] == pytest.approx(2 / 6)


def test_trailing_window_is_bounded(con):
    """d30 must not reach back further than 30 days."""
    con.execute("""
        insert into pitches values
            (1, date '2024-01-01', 0, 1.0),
            (1, date '2024-01-01', 0, 1.0)
    """)
    con.execute(f"create table spine as {FORM_SPINE_SQL}")
    row = con.execute(
        "select d30_n, career_n from spine where game_date = date '2024-04-03'"
    ).fetchone()
    assert row[0] == 4, "d30 must exclude the January rows"
    assert row[1] == 6, "career must include them"
